config/routes.rb
Rails.application.routes.draw do
  resources :kindergartens
  root 'kindergartens#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :kindergartens, dependent: :destroy
end

app/models/kindergarten.rb
class Kindergarten < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_and_belongs_to_many :pets
  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :phone, presence: true
  validates :city_id, presence: true
  validates :image, presence: true

  paginates_per 10

  def self.ransackable_attributes(auth_object = nil)
    ["city_id", "created_at", "description", "id", "name", "phone", "price", "updated_at", "user_id"]
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_and_belongs_to_many :kindergartens
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :kindergartens, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kindergartens_controller.rb
class KindergartensController < ApplicationController
  before_action :set_kindergarten, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /kindergartens or /kindergartens.json
  def index
    @q = Kindergarten.ransack(params[:q])
    @kindergartens = @q.result(distinct: true).page(params[:page])

    if @kindergartens.count == 0
      flash[:notice] = "Sin resultados"
    end
  end

  # GET /kindergartens/1 or /kindergartens/1.json
  def show
  end

  # GET /kindergartens/new
  def new
    @kindergarten = current_user.kindergartens.build
  end

  # GET /kindergartens/1/edit
  def edit
  end

  # POST /kindergartens or /kindergartens.json
  def create
    @kindergarten = current_user.kindergartens.build(kindergarten_params)

    respond_to do |format|
      if @kindergarten.save
        format.html { redirect_to kindergarten_url(@kindergarten), notice: "Kindergarten was successfully created." }
        format.json { render :show, status: :created, location: @kindergarten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kindergarten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kindergartens/1 or /kindergartens/1.json
  def update
    respond_to do |format|
      if @kindergarten.update(kindergarten_params)
        format.html { redirect_to kindergarten_url(@kindergarten), notice: "Kindergarten was successfully updated." }
        format.json { render :show, status: :ok, location: @kindergarten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kindergarten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kindergartens/1 or /kindergartens/1.json
  def destroy
    @kindergarten.destroy

    respond_to do |format|
      format.html { redirect_to kindergartens_url, notice: "Kindergarten was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kindergarten
      @kindergarten = Kindergarten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kindergarten_params
      params.require(:kindergarten).permit(:name, :description, :city_id, :phone, :user_id, :image, :price,:pet_ids => [])
    end

    def authorize_user
    unless @kindergarten.user == current_user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to @kindergarten
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kindergartens_helper.rb
module KindergartensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/kindergartens/_form.html.erb
<%= form_with(model: kindergarten, class: "row g-3") do |form| %>
  <% if kindergarten.errors.any? %>
    <div class="col-md-12" style="color: red">
    
        <% kindergarten.errors.each do |error| %>
          
        <div class="alert alert-danger alert-dismissible fade show border-0 shadow-sm" role="alert">
          <%= error.message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <% end %>
     
    </div>
  <% end %>
  <div class="col-md-12">
  <label for="file-input">
    <div id="preview" class="preview"></div>
      <%= form.label :image, "Imagen de portada", class: "form-label" %>
      <%= form.file_field :image, class: "form-control", id: 'file-input', onChange: 'getImagePreview(event)' %>
    </div>
  </label>
  <div class="col-md-6">
    <%= form.label :name, "Titulo", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="col-md-6">
    <%= form.label :phone, "Teléfono", class: "form-label" %>
    <%= form.number_field :phone, class: "form-control" %>
  </div>
  <div class="col-md-6">
    <%= form.label :price, "Precio", class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="col-md-6">
    <%= form.label :city_id, "Ciudad", class: "form-label" %>
    <%= form.collection_select :city_id, City.all, :id, :name, { prompt: "Elije una ciudad" }, class: "form-select" %>
  </div>
  <div class="col-md-12">
    <%= form.label :description, "Descripción", class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
<div class="col-md-12">
  <%= form.label :pet_ids, "Mascotas aceptadas", class: "form-label" %>
  <ul class="list-unstyled row row-cols-2 row-cols-md-5 mb-3 col-12">
    <% Pet.all.each do |pet| %>
      <li class="col">
        <div class="form-check">
          <%= form.check_box :pet_ids, { multiple: true, class: "form-check-input" }, pet.id, nil %>
          <%= form.label :pet_ids, pet.name, class: "form-check-label" %>
        </div>
      </li>
    <% end %>
  </ul>
</div>


  <div class="col-md-12">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  function getImagePreview(event) {
    let image = URL.createObjectURL(event.target.files[0]);
    let icon = document.getElementById('icon');
    let imagediv = document.getElementById('preview');
    let newimg = document.createElement('img');
    imagediv.innerHTML = '';
    newimg.src = image;
    imagediv.appendChild(newimg);
    icon.style.display = 'none';
  }
</script>

app/views/kindergartens/_kindergarten.html.erb
  <%= image_tag kindergarten.image, class: "w-100 rounded-2 shadow card-img-top
" if kindergarten.image.attached? %>
<div id="<%= dom_id kindergarten %>" class="card shadow border-0 my-3">
  <div class="card-body">
    <h3 class="card-title fw-bold"><%= kindergarten.name %></h3>
    <p class="text-muted"><%= kindergarten.description %></p>
    <div class="row mt-4">
        <p><strong>Disponible en:</strong> <%= kindergarten.city.name %></p>
        <p><strong>Mascotas permitidas:</strong> <%= kindergarten.pets.map(&:name).join(", ") %></p>
      <div class="col-md-6">
        <p><strong>Llamanos al:</strong> <%= kindergarten.phone %></p>
      </div>
      <div class="col-md-6">
        <p><strong>Contáctanos en:</strong> <%= kindergarten.user.email %></p>
      </div>
        <p class=" fs-1 fw-bold text-success"><%= number_to_currency(kindergarten.price, precision: 0, delimiter: ".", separator: ",") %></p>
    </div>
  </div>
</div>

app/views/kindergartens/edit.html.erb
<h1>Editar</h1>

<%= render "form", kindergarten: @kindergarten %>

app/views/kindergartens/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= search_form_for @q, url: :kindergartens, html: { class: "form-inline" } do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nombre", class: "sr-only" %>
          <%= f.search_field :name_cont, class: "form-control mr-sm-2", placeholder: "Buscar por nombre" %>
        </div>
        <div class="form-group">
          <%= f.label :city_id_eq, "Ciudad", class: "sr-only" %>
          <%= f.collection_select :city_id_eq, City.all, :id, :name, { include_blank: true }, { class: "form-control mr-sm-2" } %>
        </div>
        <div class="d-grid gap-2">
          <%= f.submit "Buscar", class: "btn btn-primary my-3" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-9">
      <div id="kindergartens" class="list-group">
        <div class="row row-cols-1 row-cols-md-2 g-4">
          <% @kindergartens.each do |kindergarten| %>
            <%= link_to kindergarten_path(kindergarten), class: "text-decoration-none text-black" do %>
              <div class="col">
                <div id="<%= dom_id kindergarten %>" class="card h-100 shadow border-0 mb-3">
                  <%= image_tag kindergarten.image, class: "card-img-top" if kindergarten.image.attached? %>
                  <div class="card-body">
                    <h4 class="fw-bold"><%= kindergarten.name %></h4>
                      <p><strong>Disponible en:</strong> <%= kindergarten.city.name %></p>
                      <p><strong>Mascotas permitidas:</strong> <%= kindergarten.pets.map(&:name).join(", ") %></p>               
                      <p class=" fs-2 fw-bold text-success"><%= number_to_currency(kindergarten.price, precision: 0, delimiter: ".", separator: ",") %></p>         
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <%= paginate @kindergartens, class: "pagination justify-content-center" %>
      </div>
    </div>
  </div>
</div>

app/views/kindergartens/new.html.erb
<h1>Nueva Guarderia</h1>

<%= render "form", kindergarten: @kindergarten %>

app/views/kindergartens/show.html.erb
<%= render @kindergarten %>

<% if @kindergarten.user == current_user%>
  <div class="interactive-btns">
    <%= link_to "Editar", edit_kindergarten_path(@kindergarten), class: 'btn btn-warning' %>
    <%= button_to "Eliminar", @kindergarten, method: :delete, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsToHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mt-3 pb-5">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show border-0 shadow-sm" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show border-0 shadow-sm" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-body-tertiary">
    <div class="container">
        <%= link_to "PetsToHome", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <% if current_user%>
                    <li class="nav-item">
                        <%= link_to "Crear guardería", new_kindergarten_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: 'nav-link' %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Ingreso", new_user_session_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Registro", new_user_registration_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>